# Defines the ros parameters which define the characteristics of this host vehicle configuration

# String: Host vehicle make
vehicle_make: 'Freightliner'

# String: Host vehicle model
vehicle_model: 'Cascadia'

# Integer: Host vehicle year
# Units: Year
vehicle_year: 2012

# Double: Host vehicle length
# Units: Meters
# TODO update value based on measurements
vehicle_length: 6.0

# Double: Host vehicle width
# Units: Meters
# TODO update value based on measurements
vehicle_width: 3.0

# Double: Host vehicle height
# Units: Meters
# TODO update value based on measurements
vehicle_height: 3.0

# Double: Distance from front axel to rear axel
# Units: Meters
vehicle_wheel_base: 5.334

# Double: Radius of the tires
# Units: Meters
vehicle_tire_radius: 0.5715

# Acceleration limit
# Units: m/s^2
vehicle_acceleration_limit: 3.0

# Deceleration limit
# Units: m/s^2
vehicle_deceleration_limit: 6.0

# Lateral Acceleration Limit
# Units: m/s^2
vehicle_lateral_accel_limit: 2.5

# Lateral Jerk Limit
# Units: m/s^3
vehicle_lateral_jerk_limit: 2.0

# Max curvature rate
# Units: (m^-1) / s
vehicle_max_curvature_rate: 0.75

#  (radians of a full steering wheel rotation) / (radians of tires with the longitudinal axis under full steer)
vehicle_steering_gear_ratio: 20.689

# Maximum steering angle
# Unit: deg
vehicle_steer_lim_deg: 41.5

# steering dynamics time constant 
# Unit: s
vehicle_model_steer_tau : 0.3

#Parameter to switch between passeger car and truck
truck: true
car: false

# Required drivers for the vehicle to be functional
required_drivers:
  - /hardware_interface/ssc_interface_wrapper
lidar_gps_drivers:
  - /hardware_interface/velodyne_1/velodyne_lidar_driver_wrapper 
  - /hardware_interface/velodyne_2/velodyne_lidar_driver_wrapper 
  - /hardware_interface/novatel_gps_nodelet_wrapper





