# Defines the ros parameters which define the characteristics of this host vehicle configuration
# The value type field is used to indicate how the field should be set. 
# Should it be treated as a measured value (Measured) or a desired behavior constraint (Desired)

# String: Host vehicle make
# Value type: Measured
vehicle_make: 'Freightliner'

# String: Host vehicle model
# Value type: Measured
vehicle_model: 'Cascadia'

# Integer: Host vehicle year
# Value type: Measured
# Units: Year
vehicle_year: 2012

# Double: Host vehicle length
# Value type: Measured
# Units: Meters
# TODO update value based on measurements
vehicle_length: 6.0

# Double: Host vehicle width
# Value type: Measured
# Units: Meters
# TODO update value based on measurements
vehicle_width: 3.0

# Double: Host vehicle height
# Value type: Measured
# Units: Meters
# TODO update value based on measurements
vehicle_height: 3.0

# Double: Distance from front axel to rear axel
# Value type: Measured
# Units: Meters
vehicle_wheel_base: 5.334

# Double: Radius of the tires
# Value type: Measured
# Units: Meters
vehicle_tire_radius: 0.5715

# Acceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_acceleration_limit: 2.0

# Deceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_deceleration_limit: 2.0

# Lateral Acceleration Limit
# Value type: Desired
# Units: m/s^2
vehicle_lateral_accel_limit: 2.5

# Lateral Jerk Limit
# Value type: Desired
# Units: m/s^3
vehicle_lateral_jerk_limit: 2.0

# Max curvature rate
# Value type: Desired
# Units: (m^-1) / s
vehicle_max_curvature_rate: 0.75

# Ratio relating the steering wheel angle and the tire position on the road
# Value type: Measured
# (radians of a full steering wheel rotation) / (radians of tires with the longitudinal axis under full steer)
vehicle_steering_gear_ratio: 20.689

# Maximum steering angle of the wheel relative to the vehicle centerline.
# Value type: Measured
# Unit: deg
vehicle_steer_lim_deg: 41.5

# steering dynamics time constant 
# Value type: Measured 
# Unit: s
vehicle_model_steer_tau : 0.3

# Parameter to switch between passenger car and truck
# Value type: Measured 
truck: true
car: false

# Required drivers for the vehicle to be functional
required_drivers:
  - /hardware_interface/ssc_interface_wrapper
lidar_gps_drivers:
  - /hardware_interface/velodyne_1/velodyne_lidar_driver_wrapper 
  - /hardware_interface/velodyne_2/velodyne_lidar_driver_wrapper 
  - /hardware_interface/novatel_gps_nodelet_wrapper
camera_drivers:
  - /hardware_interface/camera

# Vehicle Participation Type
participation_type: "vehicle:truck"

# Parameter to enable configurable speed limit
# Value type: Desired
config_speed_limit: 45.0

# Topics to exclude from rosbag recording
exclude_default: true
excluded_default_topics:
  - /rosout(.*)
  - (.*)/received_messages
  - (.*)/sent_messages
  - (.*)/scan
  - (.*)/compressed(.*)

exclude_lidar: true
excluded_lidar_topics:
  - /detection/lidar_detector/objects
  - /detection/lidar_detector/objects_markers
  - /hardware_interface/lidar/points_raw
  - /hardware_interface/camera/projection_matrix/detection/lidar_detector/cloud_clusters
  - /environment/range_vision_fusion_01/detection/lidar_detector/objects
  - /environment/detection/fusion_tools/objects
  - /environment/detection/fusion_tools/objects_markers
  - /environment/detection/object_tracker/objects
  - /environment/detection/object_tracker/objects_markers
  - /environment/detection/objects
  - /hardware_interface/velodyne_1/lidar/points_raw
  - /hardware_interface/velodyne_2/lidar/points_raw
  
exclude_camera: true
excluded_camera_topics:
  - /hardware_interface/camera/camera_info
  - /hardware_interface/camera/image_raw
  - /hardware_interface/camera/image_rect
  - /hardware_interface/camera/image_rects
  - /hardware_interface/camera/projection_matrix/detection/lidar_detector/cloud_clusters
  - /environment/range_vision_fusion_01/detection/image_detector/objects
  - /environment/vision_beyond_track_01/detection/image_detector/objects
  - /environment/detection/fusion_tools/objects
  - /environment/detection/fusion_tools/objects_markers
  - /environment/detection/object_tracker/objects
  - /environment/detection/object_tracker/objects_markers
  - /environment/detection/objects

exclude_can: true
excluded_can_topics:
  - /hardware_interface/ds_fusion/can_bus_dbw/can_rx 
  - /hardware_interface/ds_fusion/can_bus_dbw/can_tx