# Defines the ros parameters which define the characteristics of this host vehicle configuration
# The value type field is used to indicate how the field should be set. 
# Should it be treated as a measured value (Measured) or a desired behavior constraint (Desired)

# String: Host vehicle make
# Value type: Measured
vehicle_make: 'Traxxas'

# String: Host vehicle model
# Value type: Measured
vehicle_model: 'Slash 4X4 Platinum'

# Integer: Host vehicle year
# Value type: Measured
# Units: Year
vehicle_year: 2012

# Double: Host vehicle length
# Value type: Measured
# Units: Meters
vehicle_length: 0.568

# Double: Host vehicle width
# Value type: Measured
# Units: Meters
vehicle_width: 0.296

# Double: Host vehicle height
# Value type: Measured
# Units: Meters
vehicle_height: 0.193

# Double: Distance from front axel to rear axel
# Value type: Measured
# Units: Meters
vehicle_wheel_base: 0.324

# Double: Radius of the tires
# Value type: Measured
# Units: Meters
vehicle_tire_radius: 0.055

# Acceleration limit
# Value type: Desired
# Units: m/s^2
# vehicle_acceleration_limit: 

# Deceleration limit
# Value type: Desired
# Units: m/s^2
# vehicle_deceleration_limit: 

# Lateral Acceleration Limit
# Value type: Desired
# Units: m/s^2
# vehicle_lateral_accel_limit: 

# Lateral Jerk Limit
# Value type: Desired
# Units: m/s^3
# vehicle_lateral_jerk_limit: 

# Max curvature rate
# Value type: Desired
# Units: (m^-1) / s
# vehicle_max_curvature_rate: 

# Ratio relating the steering wheel angle and the tire position on the road
# Value type: Measured
# (radians of a full steering wheel rotation) / (radians of tires with the longitudinal axis under full steer)
# vehicle_steering_gear_ratio: 

# Maximum steering angle of the wheel relative to the vehicle centerline.
# Value type: Measured
# Unit: deg
# vehicle_steer_lim_deg: 

# steering dynamics time constant 
# Value type: Measured 
# Unit: s
# vehicle_model_steer_tau : 

# Parameter to switch between passenger car and truck
# Value type: Measured
truck: false
car: true

# Required drivers for the vehicle to be functional
required_drivers:
  - /hardware_interface/c1t_vesc_driver
lidar_gps_drivers: 
  - /hardware_interface/c1t_rplidar_driver
camera_drivers: 
  - /hardware_interface/c1t_zed_driver
