# Defines the ros parameters which define the characteristics of this host vehicle configuration
# The value type field is used to indicate how the field should be set. 
# Should it be treated as a measured value (Measured) or a desired behavior constraint (Desired)

# String: Host vehicle make
# Value type: Measured
vehicle_make: 'Lexus'

# String: Host vehicle model
# Value type: Measured
vehicle_model: 'RX-450'

# Integer: Host vehicle year
# Value type: Measured
# Units: Year
vehicle_year: 2019

# Double: Host vehicle length
# Value type: Measured
# Units: Meters
vehicle_length: 5.0

# Double: Host vehicle width
# Value type: Measured
# Units: Meters
vehicle_width: 2.5

# Double: Host vehicle height
# Value type: Measured
# Units: Meters
vehicle_height: 3.0

# Double: Distance from front axel to rear axel
# Value type: Measured
# Units: Meters
vehicle_wheel_base: 2.79

# Double: Radius of the tires
# Value type: Measured
# Units: Meters
vehicle_tire_radius: 0.39

# Acceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_acceleration_limit: 3.0

# Deceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_deceleration_limit: 6.0

# Lateral Acceleration Limit
# Value type: Desired
# Units: m/s^2
vehicle_lateral_accel_limit: 2.5

# Lateral Jerk Limit
# Value type: Desired
# Units: m/s^3
vehicle_lateral_jerk_limit: 2.0

# Max curvature rate
# Value type: Desired
# Units: (m^-1) / s
vehicle_max_curvature_rate: 0.75

# Ratio relating the steering wheel angle and the tire position on the road
# Value type: Measured
# (radians of a full steering wheel rotation) / (radians of tires with the longitudinal axis under full steer)
vehicle_steering_gear_ratio: 16.863

# Maximum steering angle of the wheel relative to the vehicle centerline.
# Value type: Measured
# Unit: deg
vehicle_steer_lim_deg: 29.2

# steering dynamics time constant 
# Value type: Measured
# Unit: s
vehicle_model_steer_tau : 0.3

# Parameter to switch between passenger car and truck
truck: false
car: true 

# Required drivers for the vehicle to be functional
required_drivers:
  - /hardware_interface/ssc_interface_wrapper
lidar_gps_drivers:
  - /hardware_interface/velodyne_lidar_driver_wrapper
  - /hardware_interface/novatel_gps_nodelet_wrapper

# Parameter to enable configurable speed limit
config_speed_limit: 45.0